services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice_ocr  
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
      - llm-service
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/invoice_ocr"
    ports:
      - "4000:4000"

  llm-service:
    build: ./llm-service
    ports:
      - "5001:5000"

volumes:
  pgdata:
